name: Run Colab Notebook

on:
  schedule:
    - cron: '0 8 * * *'  # Schedules the job to run every day at 8am UTC
  workflow_dispatch:

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.12'  # Ensure this matches the Python version used in your notebook

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nbconvert nbformat

    - name: Run Colab Notebook
      run: |
        jupyter nbconvert --to notebook --execute --inplace Practice_KatherineAnne.ipynb
